### ISSUE TITLE
服务后台停止服务，进程没有kill掉

### ISSUE THREAD

**Issue by a289459798** [luoxiaojun1992/lumen-tars-demo#4]
基础信息：
服务器版本：mac0S 10.14.6 
环境：docker方式安装
程序：基于http协议的lumen原生开发方式

问题描述：
在服务后台发布节点成功之后，停止服务，进程没有完全kill掉，只是kill了一个进程，然后重启之后，又会重新fork进程，反复操作，会出现很多僵尸进程

截图（如有）：

发布成功之后：
![image](https://user-images.githubusercontent.com/3126111/63245556-1207e880-c293-11e9-9b07-7a1b26aa92b9.png)

停止服务之后：
![image](https://user-images.githubusercontent.com/3126111/63245590-26e47c00-c293-11e9-9df6-6e069b5f338b.png)

只kill掉了图1 中的红色方框的进程号

**Comment by luoxiaojun1992** [comment]
你好，
请在/usr/local/app/tars/tarsnode/data/ichong.UserService/bin目录下手动执行
```shell
bash tars_stop.sh
```
试一下，谢谢。
