### ISSUE TITLE
请问路由/Laravel/route前缀是在哪里限制的 ？

### ISSUE THREAD

**Issue by ronylee** [luoxiaojun1992/lumen-tars-demo#5]
请问路由/Laravel/route前缀是在哪里限制的， 可以修改么？

**Comment by luoxiaojun1992** [comment]
暂时不支持，我会找时间改造成用自定义路由的方式，去掉/Laravel/route的前缀，完全用laravel的路由

**Comment by ronylee** [comment]
/Laravel/route 这个前缀用于项目，是完全不能接受的，其它功能都挺满足需求的。

`luoxiaojun1992\laravel-tars\src\controller\LaravelController.php `

这里还是tars原来的路由规则

我看tars-server有扩展了lumen路由出来

`        // 实例化服务器容器，注册事件，路由服务提供者
        $app = new Container;
        with(new EventServiceProvider($app))->register();
        with(new RoutingServiceProvider($app))->register();

        // 加载路由 路由文件的位置是否支持可配置？
        require __DIR__.'/../../../../../app/Http/routes.php';

        // 将 TarsRequest 转为 LumenRequest
        $illuminateRequest = $this->makeRequest($request);
        
        // 路由
        $illuminateResponse = $app['router']->dispatch($illuminateRequest);
    
        // 将 LumenResponse 转为 TarsResponse
        $this->send($illuminateResponse, $response);`

但是试了一下， require __DIR__.'/../../../../../app/Http/routes.php'; 引入路由文件，不能定义路由，$router 提示未定义

**Comment by luoxiaojun1992** [comment]
LumenRoute是独立于Laravel或者Lumen的路由引擎，并不是和Lumen完全结合了。

**Comment by ronylee** [comment]
好的，谢谢！

**Comment by luoxiaojun1992** [comment]
修改已发布，详见 https://github.com/luoxiaojun1992/laravel-tars/releases/tag/0.1.5
tars-server包依赖了illuminate5.5，所以目前只支持5.5版本的框架。

@ronylee

**Comment by ronylee** [comment]
好的，谢谢 ！
