### ISSUE TITLE
用tars传输字符串类型数据量较大时日志报如下错误，接受的数据是空的

### ISSUE THREAD

**Issue by wx1860** [luoxiaojun1992/lumen-tars-demo#8]
lumen.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ErrorException: Undefined offset: 2 in /data/tars/tarsnode-data/Kdy.RpcServer/bin/src/vendor/phptars/tars-server/src/core/Server.php:509
Stack trace:
#0 /data/tars/tarsnode-data/Kdy.RpcServer/bin/src/vendor/phptars/tars-server/src/core/Server.php(509): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Undefined offse...', '/data/tars/tars...', 509, Array)
#1 {main}
  thrown in /data/tars/tarsnode-data/Kdy.RpcServer/bin/src/vendor/phptars/tars-server/src/core/Server.php:509
Stack trace:
#0 /data/tars/tarsnode-data/Kdy.RpcServer/bin/src/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php(54): Laravel\Lumen\Application->handleShutdown()
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#2 {main}

主要传递base64字符串,数据大小string(59419)，如果将字符串数据变小，日志不会出现错误，并能正常接受请求参数

**Comment by luoxiaojun1992** [comment]
看上去像是 tars-server 包的错误，应该到对应项目反馈issue

https://github.com/TarsPHP/tars-server
